from alexa import input_card
from alexa import util
import datetime

input_card.read_data("alexa/sample.json")

util.test()
print ("TEST: all correct")
print("Current date: {}".format(util.get_current_date()))
q = util.get_question()
print("q: {}".format(q))
a = util.get_answer()
print("a: {}".format(a))
util.set_score(5)
q = util.get_question()
print("q: {}".format(q))
a = util.get_answer()
print("a: {}".format(a))
util.set_score(5)
util.test()
print("Current date: {}".format(util.get_current_date()))
util.move_date(1)
print("Current date: {}".format(util.get_current_date()))

print("TEST: first incorrect")
print(util.any_questions_left())
q = util.get_question()
print("q: {}".format(q))
a = util.get_answer()
print("a: {}".format(a))
print(util.any_questions_left())
util.set_score(0)
q = util.get_question()
print("q: {}".format(q))
a = util.get_answer()
print("a: {}".format(a))
util.set_score(5)
print(util.any_questions_left())
util.test()
print("Current date: {}".format(util.get_current_date()))
util.move_date(1)
print("Current date: {}".format(util.get_current_date()))


print("TEST: one qn given, do wrong")
print(util.any_questions_left())
q = util.get_question()
print("q: {}".format(q))
a = util.get_answer()
util.set_score(0)
print(util.any_questions_left())
util.test()
